### ISSUE TITLE
Separating selector and declaration

### ISSUE THREAD

**Issue by zannain** [Hilawol/TeaCozy#2]
It's a good idea to familiarize yourself with a [style guide](https://google.github.io/styleguide/htmlcssguide.html#Selector_and_Declaration_Separation) to ensure you are writing code that adheres to best practices. I recommend delineating selectors with a new line and a comma and separating the [declarations](https://github.com/Hilawol/TeaCozy/blob/master/resources/style.css#L19-L21) as this makes the styles more readable. 

```css
h2, h3, h4, h5 {
  padding: 10px;
  margin: 0;
}
```

```css
h2, 
h3, 
h4, 
h5 {
  padding: 10px;
  margin: 0;
}
```
